### ISSUE TITLE
Make vertical tab spacing configurable

### ISSUE THREAD

**Issue by Vodes** [vincenzopalazzo/material-ui-swing#135]
Could be that its already possible to do but i dont know how.
Also maybe add an option that allows you to use the beta styling (without the colored rect on the selected tab).

1.1.1-rc2:
![ALbqAfwwRovTdVY](https://user-images.githubusercontent.com/48185123/81591825-4ee5b380-93bd-11ea-8639-98a59cf44403.png)

1.1.1-beta (which is what i used before): 
![beFmprAYnYboTXm](https://user-images.githubusercontent.com/48185123/81591937-80f71580-93bd-11ea-9b55-4d3087b67e70.png)

**Comment by vincenzopalazzo** [comment]
HI @Vodes.

Thanks so much to test the library version rc2.

I added the possibility to set the Tab height from UIManager but I don't want that you will use the UIManager to configure the propriety because the name propriety in the future can change.

You can create your personal theme to set your personal configuration.

You can use the following code


```
import mdlaf.themes.JMarsDarkTheme;

public class ThemeExampleChangeTabHeight extends JMarsDarkTheme {

	@Override
	public int getHeightTabTabbedPane() {
		return 25;
	}
}
```

Can set the theme with the following code

`UIManager.setLookAndFeel(new MaterialLookAndFeel(new ThemeExampleChangeTabHeight()));`

You can found the code [here](https://github.com/vincenzopalazzo/material-ui-swing/tree/master/src/test/java/integration/gui/mock/component)

P.S: With the version 1.1.1 official you will have by default the height tab equal to 18.

**Comment by Vodes** [comment]
Okay thanks for letting me know. It was a little cramped xD

**Comment by vincenzopalazzo** [comment]
Hi @Vodes,

Yes you have right :)

Thanks for your feedback, let me know if you want try to implement or change any effect.

**Comment by vincenzopalazzo** [comment]
Fixed into https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/v1.1.1-rc3

Thank you.
