### ISSUE TITLE
Setting icon on JButton loses it's border

### ISSUE THREAD

**Issue by srcarter3** [vincenzopalazzo/material-ui-swing#151]
When using the .setIcon() method on an instance of JButton, it somehow overrides the border and changes it.

Note: this is using custom colors, so it looks different than the default material components, but setting the icon still shouldn't change the border.

This is what a button looks like with just a title, no icon:
![image](https://user-images.githubusercontent.com/21114460/96056147-0ab27f80-0e43-11eb-8dab-dbc2ae31b17e.png)

And this is what it looks like once I add the following lines:
`exportBtn.setIcon(downIcon);`
`exportBtn.setHorizontalTextPosition(SwingConstants.LEFT);`

![image](https://user-images.githubusercontent.com/21114460/96056525-0e92d180-0e44-11eb-84fc-8b671216fe67.png)

The rollover coloring still works:
![image](https://user-images.githubusercontent.com/21114460/96056550-1c485700-0e44-11eb-8db3-3084dcbbf8a8.png)

Thanks.

**Comment by vincenzopalazzo** [comment]
Hi @srcarter3,

Sorry for the delay in to the answer.

The button has two different states with the default material themes as JMarsDark, such a:

- Button without icon: by default contains the border;
- Button with icon: by default is without an icon, is possible to change the default configuration in different ways, such as:
    - Inside the **JMarsDark** theme, override the method `getButtonBorderEnableToAll` and return true or use the UIManager, with the following code `UIManager.put("Button[border].toAll", true);`

However, you could want to have the default behavior and want only some button with the custom style, in this case, you could implement your personal UI and use the MaterialButtonUI to develop your style.

A possible example can be the code inside the [wiki](https://github.com/vincenzopalazzo/material-ui-swing/wiki/Material-Component-Supported#implement-contained-button-with-materialbuttonui) and you can use the propriety `buttonBorderToAll` from MaterialButtonUI and set it to true inside the method `installUI` after `super.installUI` call

Maybe the button API is very complex to use to enable one single button, but in my opinion, is very powerful to support the different style of the theme without using some strange code to make difficult maintain in the time.

A MaterialButtonUI 101 can be the [wiki](https://github.com/vincenzopalazzo/material-ui-swing/wiki/Material-Component-Supported). It contains bad English, I'm so sorry about that, and also I didn't have time to finish it is a draft but it is a good start point.

Let me know if I answered your question and I fixed your problem, otherwise, let me know and I try to fix my description.

**Comment by zanderson9** [comment]
Hello Shay, @srcarter3,

based on Vincent's reply, please do **not** override settings in UIManager, "borderToAll", as that will effect other icon-buttons in JMARS UI which DO NOT need the border, such as toolbar buttons and several others.

Please use the proposed option of installing personal component UI, instead. There are examples of installing personal UI for a button in JMARS.

Thank you.

**Comment by vincenzopalazzo** [comment]
Yes, it is good manners don't touch the UIManager propriety directly if there are other possibilities to inject the custom config, thanks @zanderson9 :-)

**Comment by srcarter3** [comment]
Thanks for the example @vincenzopalazzo!
I was able to find an existing example in JMARS and between the two, created a new button with it's on MaterialButtonUI where I used the `buttonBorderToAll` flag.
Thanks!

**Comment by vincenzopalazzo** [comment]
@srcarter3 Happy to hear that you had fixed your problem :smile:.
