### ISSUE TITLE
Test result, change manager font Material UI

### ISSUE THREAD

**Issue by lilili87222** [vincenzopalazzo/material-ui-swing#27]
![p2](https://user-images.githubusercontent.com/2214998/55924540-dbfb8d80-5c3c-11e9-874f-0ed3f7a7b967.png)
![p3](https://user-images.githubusercontent.com/2214998/55924541-dbfb8d80-5c3c-11e9-9558-ec109b75845b.png)
![p1](https://user-images.githubusercontent.com/2214998/55924542-dc942400-5c3c-11e9-8193-119b520641d8.png)

I just run the demo3 and test,this is some screen on my pc.
1.some font not work on my pc,Chinese windows 10 or windows 7
2.file chooser Showing a bit of confusion

The effect is very cool, I can't believe that swing can be so beautiful. Especially the effect of the slider, it is amazing.
I thinks you can add a donate button in readme

**Comment by vincenzopalazzo** [comment]
Hi @lilili87222, 
I decided to put a shadow background on the jlist but I think it is a bit too accentuated, because jfileChoser uses a list to show this, the one you are displaying is a modified jfilechoser (but I think you know) and those of the sun don't have used a list but a panel apparently, I can only review my borders in the list.

As for the fonts, this repo does not want to replace mimimimarily that of atarw, in this repo besides the Toast component there is also a native font ida, for example on linux it runs with sanserif, on windows it runs with native ones and on mac the same thing, there is a possibility that I have not yet activated because I need an idea on how to do it is to run the look and feel like that of atarw but only by choosing it, in fact in my project there are some ownership files , but this is still a test function.

If my idea of ​​native fonts provides greater flexibility to the programmer I will leave it otherwise I also used to know, also because I believe I have solved the bug of pixeled font that existed on known

Thanks for your help, me and atarw are working on a donation project, I think it's ready soon.

I also believe atarw we thank you

**Comment by vincenzopalazzo** [comment]
@lilili87222, I disabled a load fonts native, now the fort should be work for your language

**Comment by lilili87222** [comment]
Missing class   MaterialFonts.java ,MaterialTextPaneUI.java,

MaterialTost can be removed from demo,alternate it with Alert may be better

**Comment by vincenzopalazzo** [comment]
The class MaterialFonst not existing in my project but exist MaterialFontFactory, because I don't load all the components to the bootstrap but just need them.
The materialTextPane not exist, I will add this support

> Missing class MaterialFonts.java ,MaterialTextPaneUI.java,

I intend to change the construction system, I will make these changes to the update of it.

I would like to keep the comp to the name toast because I would like to add other types of pop-up components of the alter type

> The materialTextPane not exist, I will add this support

**Comment by vincenzopalazzo** [comment]
Hi @lilili87222,

In the newly released version I added support for JTextPane and removed the dependencies that once again imported MaterialFonts, Removed also MaterialToat from the project.

*Thanks so much*

**Comment by lilili87222** [comment]
Hello ,I have donated 150 usd

Payment sent to Palazzo Vincenzo
April 25, 2019 at 9:15:29 AM GMT+8Transaction ID: 90132426AK975233X
Payment status: COMPLETED
Payment type: Goods and Services

And we will use this project in our project, and we will help recommend and promote this project later too.

**Comment by lilili87222** [comment]
[jiconswing.zip](https://github.com/vincenzopalazzo/material-ui-swing/files/3114876/jiconswing.zip)

I created a jiconswing demo,it was a great tool

**Comment by vincenzopalazzo** [comment]
Hello @lilili87222,

 Thank you so much for your donation, this makes me realize that I'm going in the right direction.
I have been working on this project for a year now and the difficulties are many in terms of complexity with swing but also because I am a student and the time available is never much and therefore I am forced to work when I have a bit of time advances me.

I'm about to finish the three-year course and I wanted to start after a brief experience abroad to improve my English a master's degree in software development and this gesture motivates me to go in this direction.

Thanks for the gesture and for taking my fork into consideration, I am happy that the project is now part of another real project.
I will update the readme where to add the donors and if you like the projects in which material-ui-swing is being exported.

Thanks again and good work

> Hello ,I have donated 150 usd

I will give him a look and in the versions later than 1.0 I will insert this tool into the project, Thank you very much.

Now version 1.0 is coming to a stable version, as the next few months will be difficult for me, I would like to deliver a version 1.0 which I then edit to add more complex effects that force me to redesign the way a component draws

> I created a jiconswing demo,it was a great tool

**Comment by lilili87222** [comment]
frame.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));  
cursor not work

**Comment by vincenzopalazzo** [comment]
Hi @lilili87222, 
I going to look this bug during the weekend, thanks so much

**Comment by vincenzopalazzo** [comment]
Hi @lilili87222,

I hope that I fond the problem and I have the questions for you:

- You have the problem with JtabbledPane?

Is yes, you resolve the problem disabled the mouseHover on JtabbledPane
`table.put("TabbedPane[MouseHover].enable",true);`

if no can you give me an example for your problem with the code?

**Comment by lilili87222** [comment]
frame.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
cursor icon will appear with default skin,but disappear with this skin,maybe not add a cursor icon.

**Comment by vincenzopalazzo** [comment]
@lilili87222 Yes, when you went set a new icon for the cursor, the icon do not be set, this is the consequence for the effect mouse hover.
With component have this problem, an example for the JTabbledPane this problem exists because I using a Listener for mouse motion.

When you set a now cursor what is the component do you use a mouse?

**Comment by vincenzopalazzo** [comment]
Hi @lilili87222,

A question, Which component fly over when setting a Frame.setCursor()?

I fixed a bug in the JTabbledPane and tomorrow I going to release a new version with the fix.

If tomorrow the bug persistent, I ask you if you can open an issue with an example of code for understanding the problem.

Thanks so much

**Comment by vincenzopalazzo** [comment]
@lilili87222 Released version beta 1.3, it tries to fix the but at the cursor

**Comment by vincenzopalazzo** [comment]
Marked this issue how resolved with MaterialTheming, I have described how to change the font with MaterialTheming [here](https://github.com/vincenzopalazzo/material-ui-swing/issues/87).

Thanks for your support, the work in the last version have also your contribution with your issue and your donation.

Best regards, 
Vincent.
