### ISSUE TITLE
Add action buttons to Dialog Title Panel

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#43]
Add action buttons to the Dialog Title Panel, at least "X"  button. It may be implemented as an optional feature for the library in general, but for JMARS, we would like to have the ability for users to close/exit the dialog by clicking "X". Having action buttons in a dialog panel is also per [material Dialog design spec](https://material.io/design/components/dialogs.html#full-screen-dialog), see **Behavior** section.

![DialogPanel](https://user-images.githubusercontent.com/49419742/57001813-a973ef00-6b6f-11e9-906f-eca81cf2e52a.png)

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

The JDialog in the material swing is development for not have a button exist, with these guidelines [Cosmo bootstrap](https://bootswatch.com/cosmo/) but I will try to resolve your problem because the all projects using a JDialog with a button exit, so they haven't the predisposition for the button undone.

Thanks for your help and thanks for open this problem

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9 ,

I added this change 

This is the [reference](https://github.com/vincenzopalazzo/material-ui-swing/issues/36) for the changes
I attend your feedback, thanks so much
