### ISSUE TITLE
Menu Items Spacing(2)

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#56]
Menu items spacing, ("Asteroids", "Jupiter System", "Mars System" are too close together) as seen in the image. Can space between such items be increased?

![MenuSpacing](https://user-images.githubusercontent.com/49419742/58738049-fa6a4380-83b8-11e9-9695-6581fc15bb1b.png)

**Comment by vincenzopalazzo** [comment]
Hi @atarw, I and ASU Mars Scientific Software team were working in the stable release for JMars Beta release version and weave a problem for new JMenuItem, in the photo, there is a border for JMenuItem but for some item this not work correctly, you have some Idea for fix this bug?

In the next hour, I commit the last code with the new fix, if you help me for resolving this but I'm happy

**Comment by atarw** [comment]
Sure I can take a look. Is it possible for you to post a small code sample of the JMenu for me to debug @zanderson9 ?

**Comment by vincenzopalazzo** [comment]
Hi @atarw, thanks for your help, I resolved the bug, this type of JMenuItem ("Asteroids", "Jupiter System", "Mars System") use the JMenu component and into the configuration of the UIManager for JMars the the border is wrong because all JMenuItem have BorderFactory.createEmpityBorder (5, 0, 5, 0) and the JMenu have BorderFactory.createEmpityBorder (), with new border into JMenu I resolved this problem, the code for resolve problem is

`UIManager.put("Menu.border", BorderFactory.createEmptyBorder(5, 0, 5, 0));`

**Comment by zanderson9** [comment]
This worked!
