### ISSUE TITLE
Allow to Selectively "Disable" Button-OnHover Effect

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#91]
There are several instances in JMARS were we want to click a button **without** having "On-Hover" effect to it. 

Some examples of such buttons are the Toolbar buttons, and Lat/Lon navigation arrows. 

Currently, a component that is declared as JButton, gets "On-Hover" effect by default. So to achieve **no** On-Hover, we were customizing a button and writing custom "paintComponent" for that button. This approach was sustainable for a while, but now that UI features of JMARS are expanding and we add new functionality, we also added more buttons that need **no** "On-Hover".
Customizing each of those cases is now more difficult.

Is it possible to modify the material library to allow "selective" On-Hover effect, i.e. have On-Hover by default but be able to turn it off?

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

I implement the answer to creating a little documentation.

> Currently, a component that is declared as JButton, gets "On-Hover" effect by default. So to achieve no On-Hover, we were customizing a button and writing custom "paintComponent" for that button. This approach was sustainable for a while, but now that UI features of JMARS are expanding and we add new functionality, we also added more buttons that need no "On-Hover".

For this problem exist two solution offers to the l&f.

## 1. Solution with MaterialManagerListener

MaterialManagerListener is a mode to remove the Mouse hover effect, is write for the cycle on all MouseListener of the component; this is the only solution to resolve the bug on the [JDK](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4380536).

`MaterialManagerListener.removeAllMaterialMouseListener(someButtonWitoutMouseOver);`

But I think the use of MaterialManagerListener inside the client code not is a good solution because this solution improves the coupling with the material-ui-swing.

The line guide is to use the MaterialManagerListener only inside the material-ui-swing, an example: when uninstalling the l&f. 

## 2. Solution with personal JButton

I think the better solution is to create personal JButton, with a personal ButtonUI, this is an example
```
package integration.gui.mock;

import mdlaf.components.button.MaterialButtonUI;

import javax.swing.*;

/**
 * @author https://github.com/vincenzopalazzo
 */
public class JButtonNoMouseHoverNative extends JButton {

    public JButtonNoMouseHoverNative() {
    }

    public JButtonNoMouseHoverNative(Icon icon) {
        super(icon);
    }

    public JButtonNoMouseHoverNative(String text) {
        super(text);
    }

    public JButtonNoMouseHoverNative(Action a) {
        super(a);
    }

    public JButtonNoMouseHoverNative(String text, Icon icon) {
        super(text, icon);
    }

    @Override
    protected void init(String text, Icon icon) {
        super.init(text, icon);
        System.out.println("called ****");
        setUI(new JButtonNoMouseHoverUI());
    }

    private static class JButtonNoMouseHoverUI extends MaterialButtonUI{

        @Override
        public void installUI(JComponent c) {
            mouseHoverEnabled = false;
            super.installUI(c);
        }
    }
}
```
## Conclusion

- With solution n.2, you can create a JButton where only this class is coupled with the material-ui-library and if in the future you want to remove the library you can change the code only in this class.
- With solution n.1 you don't declare the JButton with this code.

`JButton button = new JButtonNoMouseHoverNative("hello");`

but for remove the mouse hover you can calla the MaterialManagerListener, this solution coupled all the class that used the MaterialManagerListener with the material-library

**Comment by zanderson9** [comment]
Vincent, thank you. The solution 2 workes well for JMARS.

**Comment by vincenzopalazzo** [comment]
Marked this how fixed :smiley:
