### ISSUE TITLE
Need to be Able to Change Background for Disabled Button

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#96]
Can we add a feature to the library to be able to set _disabledBackground_ color on a disabled **icon button** at runtime, after Theme is loaded?

To explain: similarly to how we set _mouseHoverEnabled_ flag in @Override installUI(JComponent c) method when extending MaterialButtonUI, we need a feature to set _disabledbackground_ color to a "custom" value at runtime, different from what is set in the Theme via UIManager for a disabled button.

example use case:  I have an _icon button_ which is displayed on UI load in a **disabled** state. Its background should match the background color of its parent JPanel, which is different from _disabledBackground_ I set in the Theme at the start of my application. But without the ability to change _disabledBackground_ at runtime, I get the _disabledBackground_ of the Theme, and the look is wrong in this case. Here is the image (see **P** button).
So if I can specify _disabledBackground_ color in the @Override installUI(JComponent c) method, this will address the issue.

**Wrong look for P**:

![DisabledButton](https://user-images.githubusercontent.com/49419742/71757382-b52c5980-2e52-11ea-8fb9-52eec37b334f.png)

**Desired look for P**:

![Disabled2](https://user-images.githubusercontent.com/49419742/71757508-af834380-2e53-11ea-8948-1bfe5968828a.png)

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

The possibility to customize the disable background of the button was already implemented in the actual version of the library.

You can set the your personal buttonUI with this code

```
/**
 * @author https://github.com/vincenzopalazzo
 */
public class PersonalButtonUI extends MaterialButtonUI {


    @SuppressWarnings({"MethodOverridesStaticMethodOfSuperclass", "UnusedDeclaration"})
    public static ComponentUI createUI(JComponent c) {
        return new PersonalButtonUI();
    }

    @Override
    public void installUI(JComponent c) {
        super.installUI(c);
        super.disabledBackground = MaterialColors.LIGHT_BLUE_600;
        super.disabledForeground = MaterialColors.WHITE;
        c.setFont(MaterialFontFactory.getInstance().getFont(MaterialFontFactory.BOLD));
    }

    public void setColorDisableBackground(Color newColor){
        if(newColor == null){
            throw new IllegalArgumentException("argument null");
        }
        super.disabledBackground = newColor;
        //This is bad operation because recall the paint method of the component
        //With an wrong implementation this code can be cause the paint loop.
        this.button.repaint();
    }
}
```

With this code is possible has this effect

![](https://media.giphy.com/media/hW3eTBuPQMSoFH7FmL/giphy.gif)

You can find the code to implement this effet here for [Demo](https://github.com/vincenzopalazzo/material-ui-swing/blob/276ed5d94a4e1597da032cb30d769a37174daada/src/test/java/integration/gui/mock/DemoGUITest.java#L149) and here for the [PersonalButtonUI](https://github.com/vincenzopalazzo/material-ui-swing/blob/development/src/test/java/integration/gui/mock/PersonalButtonUI.java)

## Other information

With the Personal components UI there are some problems when you change the l&f to runtime; please pay attention to this particular.

**Comment by zanderson9** [comment]
Hi Vincent,
from your example above, I am concerned about "repaint" which may send a disabled button into an infinite loop of "paintComponent" call,,,
So to solve the problem, in my "local" version of the material swing library, I added this line of code in MaterialUIButton class, installUI method, 
_if (this.disabledBackground == null) {
 this.disabledBackground = UIManager.getColor("Button.disabledBackground");
}_

Then on the caller side, in my custom MyButtonUI, installUI method, I just set _disabledBackground = "mycolor"_, then call _super.installUI()_

This approach worked fine, and i was not concerned with the repaint issue.

Do you agree with such approach?

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

## Introduction

If I understand, your code in your local version contains this code

```
@Override
    public void installUI(JComponent c) {
        super.installUI(c);
        if (this.disabledBackground == null) {
            this.disabledBackground = "mycolor";
        }
        super.disabledBackground = MaterialColors.LIGHT_BLUE_600;
        super.disabledForeground = MaterialColors.WHITE;
        c.setFont(MaterialFontFactory.getInstance().getFont(MaterialFontFactory.BOLD));
    }
```

With this code you don't set never your "personal color" (mycolor) because the `super.install(c) ` will call `this.disabledBackground = UIManager.getColor("Button.disabledBackground");`

## Why you can repaint the JButton with the PersonalButtonUI?

If you think that the call to `setColorDisableBackground(Color color)` can cause the [loop](https://github.com/vincenzopalazzo/material-ui-swing/issues/88) on your application; I think you can relax because the setColorDisableBackground method called only inside your code.

Sure you **could** cause the loop (but that doesn't mean) with code like this

```
public class JButtonPaintLoop extends JButton {

    private PersonalButtonUI ui;

    public JButtonPaintLoop() {
        ui = new PersonalButtonUI();
        this.setUI(ui);
    }

    @Override
    public void paintComponents(Graphics g) {
        super.paintComponents(g);
        if(ui != null){
            ui.setColorDisableBackground(MaterialColors.DARKLY_BLUE);
        }
        System.out.println("LOOP");
    }
}
```

But with the method setColorDisableBackground you can update the button without implement a personal button, with code like this

```
genericJButtonInstance.setAction(new AbstractAction("I'm JButton") {
            @Override
            public void actionPerformed(ActionEvent e) {
                JButton button = (JButton) e.getSource();
                if(button.isEnabled()){
                    button.setEnabled(false);
                    PersonalButtonUI ui = (PersonalButtonUI) button.getUI();
                    ui.setColorDisableBackground(MaterialColors.LIGHT_GREEN_A100);
                }
            }
        });
```

## Conclusion

With the simple implementation of JButton the PersonalButtonUI implementation should work well if you want to change to runtime the color of JButton whent it is disabled.

But if you want obtain the following effect 

![](https://user-images.githubusercontent.com/49419742/71757508-af834380-2e53-11ea-8948-1bfe5968828a.png)

The implementation of PersonalButtonUI is simple, like this

```
public class PersonalButtonUI extends MaterialButtonUI {

    @SuppressWarnings({"MethodOverridesStaticMethodOfSuperclass", "UnusedDeclaration"})
    public static ComponentUI createUI(JComponent c) {
        return new PersonalButtonUI();
    }

    @Override
    public void installUI(JComponent c) {
        super.installUI(c);
        super.disabledBackground = super.background;
    }
}
```

**Comment by zanderson9** [comment]
Hi Vincent,

I would like to explain more about my code for installUI method because based on your reply I think you may have not interpreted my changes accurately.

You wrote:
> With this code you don't set never your "personal color" (mycolor) because the super.install(c) will call this.disabledBackground = UIManager.getColor("Button.disabledBackground");

Attached is my implementation, where the order of operations **does** take effect and the custom color gets set for **disabledBackground**. 
I am using **MaterialButtonUI** class,  **public void installUI(JComponent c)** as the base, my changes are in these lines:

>  if (disabledBackground == null) {        
            disabledBackground = UIManager.getColor("Button.disabledBackground");
        }

So if disabledbackground is not null, and provided from client code, then it is set to that value.
This code pattern follows a similar pattern as 

> mouseHoverEnabled

[installUI.txt](https://github.com/vincenzopalazzo/material-ui-swing/files/4028531/installUI.txt)

Also attached is the complete code for MaterialButtonUI class from **1.0.9** library version which I
 used to modify installUI method.

[MaterialButtonUI.java.txt](https://github.com/vincenzopalazzo/material-ui-swing/files/4028554/MaterialButtonUI.java.txt)

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

Now I understand and sorry for misunderstanding.

## Introduction

Your solution works well to set the personalization in the code and it is another style to write the code.

I want to add some details on this code inside the library

https://github.com/vincenzopalazzo/material-ui-swing/blob/74cbc1c54c285190571508781ec1863c83453480/src/main/java/mdlaf/components/button/MaterialButtonUI.java#L54-L56

This code is necessary to work with the life cycle of the system call of swing; if I don't use this style to write this code is impossible to disable the native MouseHover event.

To the difference of your code, that is

```
        if (disabledBackground == null) {        
            disabledBackground = UIManageconvention-styleodecreasesedBackground");
        }
```

and the actual code of the library, that is

https://github.com/vincenzopalazzo/material-ui-swing/blob/74cbc1c54c285190571508781ec1863c83453480/src/main/java/mdlaf/components/button/MaterialButtonUI.java#L50

is only code style; I have preferer the actual code because if I adopt your style I should add the same style to the all propriety of the MaterialButtonUI, this convention style decrases the legibility of the code (in my opinion).

An example

I preferer this code (also I was used by Sun)

```
disabledBackground = UIManager.getColor("Button.disabledBackground");
otherProp1 = UIManager.getColor("Button.otherProp1");
otherProp2 = UIManager.getColor("Button.otherProp2");
```

to this code

```
 if (disablbe paintingound == null) {        
            disabledBackgrounButtonIManager.getColor("Button.disabledBackground");
  }
 if (otherProp1 == null) {        
      otherProp1 = UIManager.getColor("Button.otherProp1");
  }
 if (otherProp2 == null) {        
     otherProp2 = UIManager.getColor("Button.otherProp2");
 }
```

## Loop Problem

All the solutions described in this issue don't create the loop event when the button will be paint, because the method install will call only when the Button is created, that is `JButton newButton = new JButton("I have created the MaterialUIButton");`.

Abaut my previus answer, that contains the code of **PersonalButtonUI** with a method **setColorDisableBackground**.

The method **setColorDisableBackAboutd** previousd in the my solution for change the color to runtime (like the ColorButton component in [JMars](https://jmars.mars.asu.edu/)).
The loop inside the ColorButis/was cause to the System call inside the ColorButton implementation, because it called/call method paintComponent inside another method paintComponent. (I causedibe it only for create an little of documentations).

## onclusion

Zoya, the conclusion are:

1. If you set the personal color inside the method install of the totonUI coaonent you don't have risck to have an loop event inside the clienispplication with both of solution described here.

2. If in anothe implementation do the JButton in yourriskication ya want use the implementatio with setColorDisableBackground, it called the button.repaint()anotherhis can cause the loop event but depend the your implementa totion in timplementationlication.

Also I think for clarify this, we can talk on slack and we can implement this effect with the real code with both solutions.

**Comment by zanderson9** [comment]
Hi Vincent, thank you for more details. yes, I agree with the code style you suggest and will work to implement the solution you suggested.
