### ISSUE TITLE
Demo swithc Look resize windows display issue + small things

### ISSUE THREAD

**Issue by jarek-insys** [vincenzopalazzo/material-ui-swing#99]
Hi Vincent @vincenzopalazzo,

1. Resize window problem after look change
a). demo start
![image](https://user-images.githubusercontent.com/59824651/72508770-9365a600-3846-11ea-81ae-4d1becf19bbe.png)
b) Java Look & Feel
![image](https://user-images.githubusercontent.com/59824651/72508864-b85a1900-3846-11ea-9a9f-9185435aa50e.png)
c) Material Style Look & Feel
![image](https://user-images.githubusercontent.com/59824651/72508932-db84c880-3846-11ea-8d55-e477a343bacb.png)

2. Different icons demo & release
![image](https://user-images.githubusercontent.com/59824651/72506607-834bc780-3842-11ea-8f1b-7368b1ec7a3c.png)

3.Label overwrite border when on 0 position
a) normal
![image](https://user-images.githubusercontent.com/59824651/72506985-4b914f80-3843-11ea-90ef-c477fc4443fd.png)
b) material
![image](https://user-images.githubusercontent.com/59824651/72507041-68c61e00-3843-11ea-8d49-f917c4c98fdd.png)

4. Split pane - not visible
a) normal
![image](https://user-images.githubusercontent.com/59824651/72507379-146f6e00-3844-11ea-988c-d8644995b1f2.png)
b) material
![image](https://user-images.githubusercontent.com/59824651/72507423-2cdf8880-3844-11ea-8720-95cd2de13d4f.png)
import java.awt.BorderLayout;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JSplitPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class SplitPaneExample extends JFrame {

   private static final long serialVersionUID = 1L;
   static {
      try {
         // UIManager.setLookAndFeel(new mdlaf.MaterialLookAndFeel(new
         // mdlaf.themes.MaterialOceanicTheme()));
         UIManager.setLookAndFeel(new mdlaf.MaterialLookAndFeel(new mdlaf.themes.MaterialLiteTheme()));
         // UIManager.setLookAndFeel(new mdlaf.MaterialLookAndFeel(new
         // mdlaf.themes.JMarsDarkTheme()));
         UIManager.put("Button.mouseHoverEnable", false); // Because the test are more difficulte with effect mouse
                                                          // hover
         JDialog.setDefaultLookAndFeelDecorated(true);
         JFrame.setDefaultLookAndFeelDecorated(false); // not support yet

      } catch (UnsupportedLookAndFeelException e) {
         e.printStackTrace();
      }
   }
   public static void main(String args[]) {
      SplitPaneExample frame = new SplitPaneExample();
      frame.setTitle("SplitPane issue example");
      frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
      frame.getContentPane().setLayout(new BorderLayout());
      JSplitPane pane = new JSplitPane();
      pane.setDividerLocation(200);
      JLabel l1 = new JLabel("L1");
      JLabel l2 = new JLabel("L2");
      pane.setLeftComponent(l1);
      pane.setRightComponent(l2);
      frame.getContentPane().add(pane, BorderLayout.CENTER);
      frame.setBounds(0, 0, 300, 300);
      frame.setVisible(true);
   }
}

5. Table header no headers split
a) normal 
![image](https://user-images.githubusercontent.com/59824651/72507594-77610500-3844-11ea-88c9-7f0b98ae43f0.png)
![image](https://user-images.githubusercontent.com/59824651/72507820-ecccd580-3844-11ea-8613-e0a0a4e9e601.png)

b) material
![image](https://user-images.githubusercontent.com/59824651/72508227-9b711600-3845-11ea-965d-2a709ed1b6aa.png)

**Comment by vincenzopalazzo** [comment]
Hi @jarek-insys,

This issue contains 5 issues, this complicates my work because I'm the only active developer on this library, so I have divided your issue into 5 new issues and I will close it-

1. [Resize window problem it compares when I change l&f](https://github.com/vincenzopalazzo/material-ui-swing/issues/100)
2. I'm closing this problem for the following reasons:
 - Your demo doesn't contain version 1.1.1_beta, so you can update your demo [here](https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/v1.1.1-beta) or you can open a new issue how you do declare the version of the library.
 - In the "Santa Claus lives in area 51" I declare **"The demo updates, you can play with it, but have the partial support to the Material theme."**. If you want test the material theme or the l&f change you should use this demo inside the project [Demo main for test](https://github.com/vincenzopalazzo/material-ui-swing/blob/masternow/src/main/java/MaterialUISwingDemo.java) and [Demo for unit test](https://github.com/vincenzopalazzo/material-ui-swing/blob/masternow/src/test/java/integration/gui/mock/DemoGUITest.java)
3. [Label overwrite border when on 0 position](https://github.com/vincenzopalazzo/material-ui-swing/issues)
4. [Split pane - not visible](https://github.com/vincenzopalazzo/material-ui-swing/issues/102)
5. [Table header no headers split](https://github.com/vincenzopalazzo/material-ui-swing/issues/103)

Sorry if I close this issue but I have some problem to scheduler more issues inside one, also I'm sorry if the demo doesn't work well but it is very difficult to work only in this project, sometimes I have difficulties to update the demo because I don't have more time.
The MaterialTheme is my idea and in alpha version, and the addition of change of l&f, implies many changes within the demo.
